"""initial migration

Revision ID: 4d2ba30133cb
Revises: 
Create Date: 2025-08-28 15:04:59.282198

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d2ba30133cb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    schema='assistant'
    )
    op.create_index(op.f('ix_assistant_users_email'), 'users', ['email'], unique=True, schema='assistant')
    op.create_index(op.f('ix_assistant_users_user_id'), 'users', ['user_id'], unique=False, schema='assistant')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_assistant_users_user_id'), table_name='users', schema='assistant')
    op.drop_index(op.f('ix_assistant_users_email'), table_name='users', schema='assistant')
    op.drop_table('users', schema='assistant')
    # ### end Alembic commands ###
