"""initial schema

Revision ID: 8a061db39490
Revises: 
Create Date: 2025-09-14 22:46:21.499868

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8a061db39490'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    schema='assistant'
    )
    op.create_index(op.f('ix_assistant_users_email'), 'users', ['email'], unique=True, schema='assistant')
    op.create_index(op.f('ix_assistant_users_user_id'), 'users', ['user_id'], unique=False, schema='assistant')
    op.create_table('meetings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('participants', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('start_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('transcript', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('merged_transcript', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('captions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['assistant.users.user_id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='assistant'
    )
    op.create_index(op.f('ix_assistant_meetings_title'), 'meetings', ['title'], unique=False, schema='assistant')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_assistant_meetings_title'), table_name='meetings', schema='assistant')
    op.drop_table('meetings', schema='assistant')
    op.drop_index(op.f('ix_assistant_users_user_id'), table_name='users', schema='assistant')
    op.drop_index(op.f('ix_assistant_users_email'), table_name='users', schema='assistant')
    op.drop_table('users', schema='assistant')
    # ### end Alembic commands ###
