"""added new column

Revision ID: b12811c68aca
Revises: 06b87642a9ff
Create Date: 2025-09-27 15:36:49.072411

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b12811c68aca'
down_revision: Union[str, None] = '06b87642a9ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meetings', sa.Column('meet_url', sa.Text(), nullable=True), schema='assistant')
    op.add_column('meetings', sa.Column('audio_object', sa.String(), nullable=True), schema='assistant')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meetings', 'audio_object', schema='assistant')
    op.drop_column('meetings', 'meet_url', schema='assistant')
    # ### end Alembic commands ###
